packages:
  - 'packages/*'

catalog:
  '@open-wc/testing': '^4.0.0'
  '@types/mocha': '^10.0.10'
  '@web/test-runner': '^0.18.2'
  '@web/test-runner-commands': '^0.9.0'
  bootstrap-italia: 'github:italia/bootstrap-italia#128fe6c79f4bc2983e1caf78dca5168f4dee2fab'
  lit: '^3.3.0'
  sass: '^1.89.0'
  typescript: '^5.5.3'
