// import '@italia/collapse/it-collapse.js';
import '@italia/accordion/it-accordion.js';
import '@italia/accordion/it-accordion-item.js';
import '@italia/breadcrumbs/it-breadcrumbs.js';
import '@italia/breadcrumbs/it-breadcrumb-item.js';
import '@italia/back-to-top/it-back-to-top.js';
import '@italia/button/it-button.js';
import '@italia/callout/it-callout.js';
import '@italia/callout/it-callout-more.js';
import '@italia/callout/it-callout-more-collapse.js';
import '@italia/checkbox/it-checkbox.js';
import '@italia/checkbox/it-checkbox-group.js';
import '@italia/chip/it-chip.js';
import '@italia/avatar/it-avatar.js';
import '@italia/dropdown/it-dropdown.js';
import '@italia/dropdown/it-dropdown-item.js';
import '@italia/icon/it-icon.js';
import '@italia/input/it-input.js';
import '@italia/modal/it-modal.js';
import '@italia/skiplinks/it-skiplinks.js';
import '@italia/popover/it-popover.js';
import '@italia/sticky/it-sticky.js';
import '@italia/video/it-video.js';
import '@italia/radio/it-radio.js';
import '@italia/radio/it-radio-group.js';
import '@italia/rating/it-rating.js';
import '@italia/rating/it-rating-item.js';

import { registerTranslation } from '@italia/i18n/i18n.js';

export { registerTranslation };
