import '@italia/accordion/it-accordion-item.js';
import '@italia/accordion/it-accordion.js';
import '@italia/autocomplete/it-autocomplete.js';
import '@italia/avatar/it-avatar.js';
import '@italia/back-to-top/it-back-to-top.js';
import '@italia/breadcrumbs/it-breadcrumb-item.js';
import '@italia/breadcrumbs/it-breadcrumbs.js';
import '@italia/button/it-button.js';
import '@italia/callout/it-callout-more-collapse.js';
import '@italia/callout/it-callout-more.js';
import '@italia/callout/it-callout.js';
import '@italia/card/it-card.js';
import '@italia/carousel/it-carousel.js';
import '@italia/checkbox/it-checkbox-group.js';
import '@italia/checkbox/it-checkbox.js';
import '@italia/chip/it-chip.js';
// import '@italia/collapse/it-collapse.js';
import '@italia/dropdown/it-dropdown-item.js';
import '@italia/dropdown/it-dropdown.js';
import '@italia/dimmer/it-dimmer.js';
import '@italia/icon/it-icon.js';
import '@italia/input/it-input.js';
import '@italia/megamenu/it-megamenu.js';
import '@italia/hero/it-hero.js';
import '@italia/modal/it-modal.js';
import '@italia/navscroll/it-navscroll.js';
import '@italia/pagination/it-pagination-item.js';
import '@italia/pagination/it-pagination.js';
import '@italia/popover/it-popover.js';
import '@italia/progress/it-progress.js';
import '@italia/radio/it-radio-group.js';
import '@italia/radio/it-radio.js';
import '@italia/rating/it-rating-item.js';
import '@italia/rating/it-rating.js';
import '@italia/section/it-section.js';
import '@italia/select/it-select.js';
import '@italia/skiplinks/it-skiplinks.js';
import '@italia/sticky/it-sticky.js';
import '@italia/tabs/it-tabs.js';
import '@italia/tabs/it-tab.js';
import '@italia/tabs/it-tab-panel.js';
import '@italia/toggle/it-toggle-group.js';
import '@italia/toggle/it-toggle.js';
import '@italia/video/it-video.js';

import { registerTranslation } from '@italia/i18n/i18n.js';

export { registerTranslation };
