import { registerTranslation } from '@italia/i18n/i18n.js';

export * from '@italia/accordion';
export * from '@italia/autocomplete';
export * from '@italia/avatar';
export * from '@italia/back-to-top';
export * from '@italia/breadcrumbs';
export * from '@italia/button';
export * from '@italia/card';
export * from '@italia/callout';
export * from '@italia/chip';
export * from '@italia/dimmer';
export * from '@italia/dropdown';
export * from '@italia/icon';
export * from '@italia/input';
export * from '@italia/megamenu';
export * from '@italia/modal';
export * from '@italia/navscroll';
export * from '@italia/notification';
export * from '@italia/pagination';
export * from '@italia/progress';
export * from '@italia/popover';
export * from '@italia/stepper';
export * from '@italia/tooltip';
export * from '@italia/radio';
export * from '@italia/section';
export * from '@italia/skiplinks';
export * from '@italia/sticky';
export * from '@italia/toolbar';
export * from '@italia/upload';
export * from '@italia/toggle';
export * from '@italia/transfer';
export * from '@italia/video';
export * from '@italia/thumbnav';

export { registerTranslation };
