name: Lint commits
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js environment
        uses: ./.github/actions/node_env_setup
        with:
          node-version: '22'

      - run: pnpm dlx commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD
