name: Code testing & coverage
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testing:
    runs-on: ubuntu-latest
    concurrency: ci-test-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node.js environment
        uses: ./.github/actions/node_env_setup
        with:
          node-version: '22'

      - name: Install playwright browsers
        run: pnpm test:setup:ci

      - name: Test
        run: pnpm test

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
